# Generated by Django 5.0 on 2023-12-27 10:38

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramasUPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(max_length=100)),
                ('tipo_titulo', models.CharField(max_length=100)),
                ('facultad', models.CharField(max_length=100)),
                ('titulo_obtenido', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Programa UPN',
                'verbose_name_plural': 'Programas UPN',
                'db_table': 'ProgramasUPN',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_doc', models.CharField(max_length=20)),
                ('documento', models.CharField(max_length=11)),
                ('numero_celular', models.CharField(max_length=20)),
                ('terminos', models.BooleanField(default=False)),
                ('es_administrativo', models.BooleanField(blank=True, default=False)),
                ('es_egresado', models.BooleanField(blank=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InformacionBasicaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo_personal', models.EmailField(max_length=254)),
                ('correo_alternativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_residencia', models.CharField(blank=True, max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=50)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('telefono_movil', models.CharField(blank=True, max_length=10)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=10, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info Basica',
                'verbose_name_plural': 'Compilado Info',
                'db_table': 'Info Basica',
            },
        ),
        migrations.CreateModel(
            name='ProgramasExternos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_titulo', models.CharField(max_length=100)),
                ('nombre_programa', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa Externo',
                'verbose_name_plural': 'Programas Externos',
                'db_table': 'ProgramasExternos',
            },
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_graduacion', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('programa_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.programasexternos')),
                ('programa_upn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.programasupn')),
            ],
            options={
                'verbose_name': 'Formación Académica',
                'verbose_name_plural': 'Formaciones Académicas',
                'db_table': 'FormacionAcademica',
            },
        ),
        migrations.CreateModel(
            name='UsuarioProgramasUPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_upn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programasupn')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Programa UPN',
                'verbose_name_plural': 'Usuarios Programas UPN',
                'db_table': 'UsuarioProgramasUPN',
            },
        ),
    ]
