# Generated by Django 5.0 on 2023-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_facultad_administrativo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacionbasicausuario',
            old_name='apellidos',
            new_name='pais_nacimiento',
        ),
        migrations.RenameField(
            model_name='informacionbasicausuario',
            old_name='telefono_movil',
            new_name='telefono_principal',
        ),
        migrations.RemoveField(
            model_name='informacionbasicausuario',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='informacionbasicausuario',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='informacionbasicausuario',
            name='correo_institucional',
        ),
        migrations.RemoveField(
            model_name='informacionbasicausuario',
            name='correo_personal',
        ),
        migrations.RemoveField(
            model_name='informacionbasicausuario',
            name='pais',
        ),
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='depa_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='depa_res',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='discapacidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='estado_civil',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='grupo_etnico',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='mun_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='mun_res',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='pais_res',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='primer_apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='sexo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='informacionbasicausuario',
            name='documento',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='informacionbasicausuario',
            name='telefono_alternativo',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='facultad_administrativo',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_administrativo',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
