# Generated by Django 5.0 on 2023-12-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_apellidos_informacionbasicausuario_pais_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionbasicausuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
