# Generated by Django 5.0 on 2023-12-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_informacionbasicausuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionbasicausuario',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
