# Generated by Django 5.0 on 2023-12-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_informacionbasicausuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='facultad_administrativo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_administrativo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
