# Generated by Django 5.0 on 2023-12-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuario_facultad_administrativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='facultad_administrativo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_administrativo',
            field=models.CharField(max_length=100),
        ),
    ]
