# Generated by Django 5.0 on 2023-12-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usuario_facultad_administrativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacionacademica',
            name='anio_graduacion',
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formacionacademica',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
