# Generated by Django 5.0 on 2023-12-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_formacionacademica_anio_graduacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programasexternos',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programasexternos',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programasupn',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programasupn',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
