# Generated by Django 5.0 on 2023-12-28 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_programasexternos_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programasexternos',
            old_name='nombre_programa',
            new_name='programa_externo',
        ),
        migrations.RenameField(
            model_name='programasupn',
            old_name='nombre_programa',
            new_name='programa',
        ),
        migrations.RenameField(
            model_name='programasupn',
            old_name='tipo_titulo',
            new_name='tipo_formacion',
        ),
    ]
